# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3, time
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Widget(object):
    def callsql(self):
        self.connection = sqlite3.connect("library.db")
        self.cursor = self.connection.cursor()

        self.cursor.execute("CREATE TABLE IF NOT EXISTS kitaplar (isim TEXT, yazar TEXT, kitapno İNT)")
        self.connection.commit()

    def setupUi(self, Widget):
        Widget.setObjectName("başarabilirsin")
        Widget.resize(1020, 652)
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(20, 100, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.lineEditName = QtWidgets.QLineEdit(Widget)
        self.lineEditName.setGeometry(QtCore.QRect(20, 140, 131, 28))
        self.lineEditName.setText("")
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditWriter = QtWidgets.QLineEdit(Widget)
        self.lineEditWriter.setGeometry(QtCore.QRect(20, 190, 131, 28))
        self.lineEditWriter.setText("")
        self.lineEditWriter.setObjectName("lineEditWriter")

        self.tabloyap = QtWidgets.QTextEdit(Widget)
        self.tabloyap.setGeometry(QtCore.QRect(390, 100, 521, 311))
        self.tabloyap.setObjectName("tablyap")

        self.lineEditNumber = QtWidgets.QLineEdit(Widget)
        self.lineEditNumber.setGeometry(QtCore.QRect(20, 230, 131, 28))
        self.lineEditNumber.setText("")
        self.lineEditNumber.setObjectName("lineEditNumber")
        self.label_5 = QtWidgets.QLabel(Widget)
        self.label_5.setGeometry(QtCore.QRect(20, 320, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEditNumberde = QtWidgets.QLineEdit(Widget)
        self.lineEditNumberde.setGeometry(QtCore.QRect(20, 350, 141, 28))
        self.lineEditNumberde.setText("")
        self.lineEditNumberde.setObjectName("lineEditNumberde")
        self.addbutton = QtWidgets.QPushButton(Widget)
        self.addbutton.setGeometry(QtCore.QRect(20, 270, 131, 29))
        self.addbutton.setObjectName("addbutton")
        self.deletebutton = QtWidgets.QPushButton(Widget)
        self.deletebutton.setGeometry(QtCore.QRect(20, 390, 141, 29))
        self.deletebutton.setObjectName("deletebutton")

        self.viewListbutton = QtWidgets.QPushButton(Widget)
        self.viewListbutton.setGeometry(QtCore.QRect(390, 60, 151, 29))
        self.viewListbutton.setObjectName("viewList")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(160, 140, 63, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(160, 190, 63, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(160, 230, 63, 20))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Widget)
        self.label_6.setGeometry(QtCore.QRect(160, 350, 63, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Widget)
        self.label_7.setGeometry(QtCore.QRect(20, 430, 140, 30))
        self.label_7.setFont(font)

        self.addbutton.clicked.connect(self.btnEkleClicked)
        self.deletebutton.clicked.connect(self.btnSilClicked)
        self.viewListbutton.clicked.connect(self.showtable)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "HAYDAR TELEKOM"))
        self.label.setText(_translate("Widget", "Kitap ekle"))
        self.label_5.setText(_translate("Widget", "Kitap sil"))
        self.addbutton.setText(_translate("Widget", "Listeye Ekle"))
        self.deletebutton.setText(_translate("Widget", "Listeden Sil"))
        self.viewListbutton.setText("liste görüntüle")
        self.label_2.setText(_translate("Widget", "Kitap Adı"))
        self.label_3.setText(_translate("Widget", "Yazarı"))
        self.label_4.setText(_translate("Widget", "Kitap no"))
        self.label_6.setText(_translate("Widget", "kitap no"))
        self.label_7.setText("işlem yapınız")

    def btnEkleClicked(self):

        name = self.lineEditName.text()
        writer = self.lineEditWriter.text()
        kitapno = self.lineEditNumber.text()
        self.cursor.execute(f"INSERT INTO kitaplar VALUES ('{name}', '{writer}', {kitapno}\n)")
        self.connection.commit()

        self.lineEditName.setText("")
        self.lineEditWriter.setText("")
        self.lineEditNumber.setText("")

        self.label_7.setText("başarıyla tamamlandı")
        time.sleep(3)
        self.label_7.setText("işlem yapınız")
        self.showtable()

    def btnSilClicked(self):
        kitapno = int(self.lineEditNumberde.text())
        self.cursor.execute(f"DELETE FROM kitaplar WHERE kitapno = {kitapno}")
        self.connection.commit()

        self.lineEditNumberde.setText("")
        self.label_7.setText("başarıyla tamamlandı")
        time.sleep(3)
        self.label_7.setText("işlem yapınız")
        self.showtable()

    def showtable(self):
        self.cursor.execute("SELECT * FROM kitaplar")
        liste = str(self.cursor.fetchall())
        self.tabloyap.setText(liste)

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.callsql()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())